### ISSUE TITLE
Villages burn with no reason.

### ISSUE THREAD

**Issue by SuzuChen** [Rebirth-of-the-Night/ToroQuestRevamped#1]
When I enter the villages, some buildings start to burn for some reason.. Dnno why, I don't have any mods installed that can cause something like that +on the older version it was fine.

**Comment by CalaMariGold** [comment]
Villages near spawn are raided villages. They burn and are raided by bandits or zombies. Can be adjusted in the config

**Comment by SuzuChen** [comment]
Do I need to set it to 0, to disable it?

**Comment by SuzuChen** [comment]
eneration {
    I:destroyedVillagesNearSpawnDistance=1
    B:useBiomeSpecificProvinces=true
spawning {
    I:banditSpawnRate=8
    I:caravanSpawnRate=12
    I:disableMobSpawningNearVillage=64
    I:enchantFirstBanditAndOrcChance=20
    I:enchantSecondBanditAndOrcChance=60
    I:fugitiveSpawnRate=8
    B:lostToroQuest=true
    I:provinceSiegeRate=0
    I:toroSpawnChance=16
}
