### ISSUE TITLE
Option to remove Cartographer trades to reduce lag spikes / server stress

### ISSUE THREAD

**Issue by barttraeger** [Rebirth-of-the-Night/ToroQuestRevamped#10]
The trades of the cartographer (maps to mansions, monuments, villages) can cause a lot of stress for the server,
as it searches for the nearest structures. After trading with him I experience constant lag spikes.
There seems to be no way to remove these trades properly since they're hardcoded in
"toroquest/entities/trades/ToroVillagerTrades.java ".
Removing the trade in the ToroQuest-config doesn't work. 
I've also tried to remove them via the mod Villager Trade Tables with different profession/career names with no luck.
Is there a method I haven't thought of or could you implement an option in the config to disable the trades ?

**Comment by ednellbasilio** [comment]
But my city is logging because I didn't fix render distance upper 5 shorts

**Comment by democat3457** [comment]
what @ednellbasilio
