### ISSUE TITLE
Unable to complete quest with gathering dirt (or other resources)

### ISSUE THREAD

**Issue by LUEZIS** [Rebirth-of-the-Night/ToroQuestRevamped#11]
I'm unable to give proper items to the village king, it just consumes the items and requests more:
![2021-07-04_17 20 55](https://user-images.githubusercontent.com/40040593/124393599-77381c00-dcfb-11eb-9491-e88365fd4fb6.png)
![2021-07-04_17 20 58](https://user-images.githubusercontent.com/40040593/124393607-80c18400-dcfb-11eb-9cbf-81eecbbe17fd.png)

**Comment by bglandolt** [comment]
fixed in later versions
