### ISSUE TITLE
B: UsetoroquestVillagers = false doesn't work?

### ISSUE THREAD

**Issue by GeflGabe** [Rebirth-of-the-Night/ToroQuestRevamped#2]
I always use Minecraft Comes Alive when playing 12.2, and been trying to add this to the new config file since the config file doesn't seem to generate with the line in the newest release, I've also tried setting "use default villagers outside of province" to both true and false and keep getting squidwards from toroquest in villages anyway.

**Comment by bglandolt** [comment]
set useDefaultVillagers to true in the latest version
