### ISSUE TITLE
[Doubt] What is it planned to do/implement in the mod?

### ISSUE THREAD

**Issue by gatoborrachon** [Rebirth-of-the-Night/ToroQuestRevamped#21]
**What is happening**
+Well, i have been looking for a while a mod that adds a deeper essence to the world, NPCs ambiented in the era where minecraft is supposed to be happening, the medieval times (old times in general), for that i found many mods: Millenaire, Ancient Warfare, MineColonies, Tektopia (Maybe these 2 are a bit offtopic), and then i remembered Torquest Revamped.

+I was looking for a mod that doesn't depends a lot on the player to let a village growth, and that doesn't rely on many vanilla features that can be totally changed by other mods (with this i mean, for example, the Animales changed by Animania), so basically all of these other mods doesn't fit on what i was looking, but Toroquest does it in almost everything, there's just one thing i wanted to ask:

+I also found that old mod called Lord of the Rings, i never tried it due to time, but by what i was able to see, you can form part of a Faction, do complex labors for yout team and even interact with the NPCs, so going to my question:

1.-What is it planned for the future of the mod? will it remain like it is? or there might be complexer updates in development for the Villages' social structure?

No problem if you are not interested on changing the mod, i really like that you can protect a villaged and do simple labors for your king, but maybe an overhaul would enrich the gameplay of the mod, just like Lord of the Rings do

**Additional Notes**
+I ask this from someone who mainly plays Tech mods (and who wants to enter into more hand-work mods, like Thaumcraft or a mod that adds a (complex) social structure), so yeah, anything related to improve the AI of the NPCs is welcome, but it might be good to keep it performant, for example: Millenaire is so heavy for performance, but even this, sometimes it seems to not work

2.- Also, you might know about a good and complete review about the mod? 

-as i said, due to my limited time, most of what i know about the mod comes from videos (and some creative tests looking for villages), and i only know that there are kingdoms with vanilla villagers and some guardians from this mod to defend it from bandits and orcs, there's a king whom you can do small labors to gain reputation and some rewards, and that's pretty much i know and the reason of this issue, but is there more?

**Comment by gatoborrachon** [comment]
a, mmm, so, there's nothing planned more than bugfixes?

**Comment by bglandolt** [comment]
As for now, not much is planned. Also I haven't seen any videos or reviews of toroquest revamped (only the original toroquest) so those videos might be outdated

(here is my response on curseforge if anyone else reads this)

vvv

Short answer:  not adding much more

 

Long answer:

 

Mods like Millenaire and Tektopia do what they do really well already. The purpose of ToroQuest Revamped was fix up a lot of issues with the original mod - guards couldn't use doors for example. I most likely will not be adding much more to the mod and focus more so on touching things up.

 

There's a popular modpack called Rebirth of The Night which will be using this mod and village mods such as millenaire don't quite fit nicely into the pack. Milleniare is almost a modpack on it's own with how much it adds, and personally, I wanted a mod that adds to villages, but doesn't add too much. At first I wasn't going to even add dialogue to guards for toroquest - as text doesn't fit well into minecraft. I really really dislike nametags or floating text which millenaire has a lot of. Oh, I also wanted bandits that weren't basically re-skinned zombies that run at you (my bandits do that too, but they are a bit smarter!) and I coudn't find a mod that did that so I added them myself :)

 

( I also didn't even plan to publish the mod at first, as it was for a personal modpack)

 

So yeah, think of toroquest as a simple village mod that can fit nicely into any RPG modpack

**Comment by gatoborrachon** [comment]
Yeah, sorry, i'm the same guy who asked this in Curseforge, i just wrote my last comment before reading that you replied to me in Curseforge, sorry
