### ISSUE TITLE
[Bug] Multiple Lords spawn inside of each other when generating village

### ISSUE THREAD

**Issue by barttraeger** [Rebirth-of-the-Night/ToroQuestRevamped#29]
ToroQuest Version: ToroQuest-Revamped-3-6-2022.jar
Forge Version: 14.23.5.2860
No other mods loaded

With the newest version there seems to be a bug when populating the village.
In the castle multiple Lords spawn on top of each other, crammed  together in one blockspace.
This happens quite frequently, but not in all villages.
It also seems that there are more guards around than usual.
Could be a bug while populating the village causing the spawn mechanism to fire multiple times.
Tested with only the newest version of ToroQuest loaded, no other mods.
Screenshot:
![2022-03-10_07 47 08](https://user-images.githubusercontent.com/57531292/157606814-60dc27fd-bb21-4b8b-9aab-8fbe33469f8a.png)

**Comment by CodexEnt** [comment]
I can confirm this behaviour through each new play test. 
I don't think it happens to EVERY lord in different provinces, only the nearest starting province that I discover,he is double-headed.
MAY also be a cause of a bug that comes up that breaks the quest line at random, perhaps the player is clicking on the 'doppleganger' and triggers the 'complete' and it confuses them and breaks the quest.
.
This does NOT happen to lords in other provinces, as they are single and they have quests of their own. Haven't got as far yet to see if their quests line breaks too. Something to check out for sure.

**Comment by EliteMeats** [comment]
i believe this has been fixed, confirmed by the dev

**Comment by CodexEnt** [comment]
ToroQuest-Revamped-3-6-2022  for Minecraft 1.12.2 as well.
.
OP is right, this bug still exists. Thought I'd come back and post the following image though, because this time they suddenly decided to separate, ha ha!
https://ibb.co/sjyJNMn

**Comment by bglandolt** [comment]
Polyarchy has been removed! Multiple kings no longer spawn in the latest version! Enjoy your dictatorship world...
