### ISSUE TITLE
Villages keep burning

### ISSUE THREAD

**Issue by Tezgittyhub** [Rebirth-of-the-Night/ToroQuestRevamped#3]
Every village i visit is always burning, i've tried disabling some settings but nothing has worked.

**Comment by thedeerirty** [comment]
I had this problem myself; are you using itemphysics?

**Comment by sranan-mang2** [comment]
Have you tried lowering the value for "destroyedVillagesNearSpawnDistance" in the config?

**Comment by Tezgittyhub** [comment]
yeah i did that and it worked. thanks
