### ISSUE TITLE
ToroQuest-Revamped-3-22-2022 : No tracking of number of planted crops so far

### ISSUE THREAD

**Issue by CodexEnt** [Rebirth-of-the-Night/ToroQuestRevamped#31]
ToroQuest-Revamped-3-22-2022, recommended Forge

Observations:
 - Do not get update on crop planted as before: eg. 3/32. No message is displayed.
 - Checking with the Lord and he tells me 0/32 seeds have been planted.
 - Breaking/Harvesting a planted item does display message, eg 0/32, so is presumably subtracting as in older version, but not adding credit

Replication:
- Multiple type worlds and clean 1.12.2 installation

Other Tests:
 - Planted 32+ seeds within province even if no message displayed, the Lord still says I planted 0/32

Other:
- Reputation is still counted through mob kills, gifts and mask submissions
- 
![no-crops-tracked](https://user-images.githubusercontent.com/97247854/159781172-3c11189a-bdf8-467e-b2eb-f4ee3187dbe4.jpg)
.

**Comment by bglandolt** [comment]
Ahhh made a dumb little mistake, I will release an update tonight ty!
