### ISSUE TITLE
Cannot find useToroVillagers option in config

### ISSUE THREAD

**Issue by hugonoss** [Rebirth-of-the-Night/ToroQuestRevamped#4]
I searched through the config and cannot find the option to disable ToroVillagers. 

This conflicts with other mods I'm using that adds other villagers, for example a Jam Guy villager from Actually Additions I spawned from a spawn egg shows up as a Toroquest villager with no trades. Parasites from Scrape and Run: Parasites also cannot infect ToroVillagers.

**Comment by Taknax** [comment]
Me too. I need this option because TQ override the EconomyInc Bankier.

**Comment by bglandolt** [comment]
this setting is back in as "useDefaultVillagers"
set this to true to disable torovillagers
